---
version: "3"

networks:
  traefik0:
    external: true

services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "traefik0"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 50M
      labels:
        traefik.enable: "false"

  traefik:
    image: containous/traefik:v1.2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/infra/traefik/traefik.toml:/traefik.toml"
      - "/data/infra/traefik/etc/traefik/acme:/etc/traefik/acme"
    networks:
      - "traefik0"
    labels: {}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 50M
      labels:
        SERVICE_IGNORE: "true"
        traefik.enable: "false"


